-- Run this migration first on a fresh database. For an existing database with
-- duplicate names, run scripts/dedupe-universities.js --dry-run, review it,
-- run the script, then rerun this migration to add the unique constraint.
CREATE TABLE IF NOT EXISTS public.universities (
  id BIGSERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT '',
  province TEXT NOT NULL DEFAULT '',
  sector TEXT NOT NULL DEFAULT 'Public' CHECK (sector IN ('Public', 'Private')),
  website_url TEXT NOT NULL DEFAULT ''
);

ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS name TEXT;
ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS city TEXT NOT NULL DEFAULT '';
ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS province TEXT NOT NULL DEFAULT '';
ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS sector TEXT NOT NULL DEFAULT 'Public';
ALTER TABLE public.universities ADD COLUMN IF NOT EXISTS website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE public.universities ALTER COLUMN name SET NOT NULL;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'universities_pkey'
      AND conrelid = 'public.universities'::regclass
  ) THEN
    ALTER TABLE public.universities ADD CONSTRAINT universities_pkey PRIMARY KEY (id);
  END IF;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT lower(trim(name))
    FROM public.universities
    GROUP BY lower(trim(name))
    HAVING count(*) > 1
  ) THEN
    RAISE NOTICE 'Duplicate university names found. Run the dedupe script, then rerun this migration.';
  ELSIF NOT EXISTS (
    SELECT 1 FROM pg_indexes
    WHERE indexname = 'universities_name_key'
      AND tablename = 'universities'
  ) THEN
    CREATE UNIQUE INDEX universities_name_key ON public.universities (lower(trim(name)));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.programs (
  id BIGSERIAL PRIMARY KEY,
  university_id BIGINT NOT NULL REFERENCES public.universities(id) ON DELETE CASCADE,
  degree_name TEXT NOT NULL,
  merit_formula TEXT
);

CREATE INDEX IF NOT EXISTS programs_university_id_idx ON public.programs(university_id);
